Repository markcyen/Battleship, pull requests merged in 2021-04, with the labels that each got.

#14 Refactor describes to context
  spec/ship_spec.rb
Labels: Refactoring

#13 Create coordinates class
  lib/coordinates.rb
  spec/coordinates_spec.rb
Labels: enhancement

#16 Refactor Coordinates
  lib/coordinates.rb
  spec/coordinates_spec.rb
Labels: Refactoring

#20 Add end to code block
  spec/board_spec.rb
Labels: bug

#23 Create ships class
  lib/ships.rb
  spec/ships_spec.rb
Labels: enhancement

#28 Refactor render
  lib/cell.rb
  lib/player.rb
  spec/cell_spec.rb
Labels: Refactoring

#29 Expose @size attribute
  lib/board.rb
Labels: enhancement

#30 Valid coord method
  lib/board.rb
  spec/board_spec.rb
Labels: Refactoring

#33 Board helper method
  lib/board.rb
  spec/board_spec.rb
Labels: Refactoring

#32 Refactor place
  lib/board.rb
Labels: Refactoring

#34 Refactor overlap method
  lib/board.rb
  lib/coordinates.rb
  spec/board_spec.rb
  spec/coordinates_spec.rb
Labels: Refactoring

#35 Add parameter to take_turn
  lib/player.rb
Labels: enhancement

#36 Fix Test
  spec/player_spec.rb
Labels: bug

#37 Refactor board cells methods
  lib/board.rb
  spec/board_spec.rb
Labels: Refactoring, enhancement

#38 Create ComputerPlayer class
  lib/computer_player.rb
  spec/computer_player_spec.rb
Labels: enhancement

#39 Computer player tests
  lib/computer_player.rb
  spec/computer_player_spec.rb
Labels: Refactoring, bug

#40 Refactor fire_upon
  lib/board.rb
  spec/board_spec.rb
Labels: Refactoring

#41 refactor Ship
  lib/computer_player.rb
  lib/ship.rb
  lib/ships.rb
  spec/computer_player_spec.rb
  spec/ship_spec.rb
  spec/ships_spec.rb
Labels: Refactoring

#43 Refactor computer player
  lib/computer_player.rb
  spec/computer_player_spec.rb
Labels: Refactoring

#44 Create humanplayer class
  lib/human_player.rb
  spec/human_player_spec.rb
Labels: enhancement

#45 Make battle ship runner
  battle_ship.rb
  lib/human_player.rb
  spec/computer_player_spec.rb
  spec/human_player_spec.rb
Labels: enhancement

#46 Fix issue with print_boards
  battle_ship.rb
Labels: bug

#47 Make battle ship runner
  lib/computer_player.rb
Labels: enhancement

#49 Fix minor typo
  battle_ship.rb
Labels: good first issue
